config/routes.rb
Rails.application.routes.draw do
  resources :data_pages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_page.rb
class DataPage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/data_pages_controller.rb
class DataPagesController < ApplicationController
  before_action :set_data_page, only: %i[ show edit update destroy ]

  # GET /data_pages or /data_pages.json
  def index
    #@data_pages = DataPage.all
    @data_pages = DataPage.page params[:page]
  end

  # GET /data_pages/1 or /data_pages/1.json
  def show
  end

  # GET /data_pages/new
  def new
    @data_page = DataPage.new
  end

  # GET /data_pages/1/edit
  def edit
  end

  # POST /data_pages or /data_pages.json
  def create
    @data_page = DataPage.new(data_page_params)

    respond_to do |format|
      if @data_page.save
        format.html { redirect_to data_page_url(@data_page), notice: "Data page was successfully created." }
        format.json { render :show, status: :created, location: @data_page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @data_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_pages/1 or /data_pages/1.json
  def update
    respond_to do |format|
      if @data_page.update(data_page_params)
        format.html { redirect_to data_page_url(@data_page), notice: "Data page was successfully updated." }
        format.json { render :show, status: :ok, location: @data_page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @data_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_pages/1 or /data_pages/1.json
  def destroy
    @data_page.destroy

    respond_to do |format|
      format.html { redirect_to data_pages_url, notice: "Data page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_page
      @data_page = DataPage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def data_page_params
      params.require(:data_page).permit(:data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_pages_helper.rb
module DataPagesHelper
end

app/views/data_pages/_form.html.erb
<%= form_with(model: data_page) do |form| %>
  <% if data_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(data_page.errors.count, "error") %> prohibited this data_page from being saved:</h2>

      <ul>
        <% data_page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_area :data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/data_pages/edit.html.erb
<h1>Editing Data Page</h1>

<%= render 'form', data_page: @data_page %>

<%= link_to 'Show', @data_page %> |
<%= link_to 'Back', data_pages_path %>

app/views/data_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4 text-primary">Data Pages</h1>

<div class="mt-4 mb-4">
  <%= page_entries_info @data_pages %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Data</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_pages.each do |data_page| %>
      <tr>
        <td><%= data_page.id %></td>
        <td><%= data_page.data %></td>
        <td><%= data_page.created_at %></td>
        <td><%= link_to 'Show', data_page %></td>
        <td><%= link_to 'Edit', edit_data_page_path(data_page) %></td>
        <td><%= link_to 'Destroy', data_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div>
  <%= paginate @data_pages%>
</div>
<br>
<%= link_to 'New Data Page', new_data_page_path %>

app/views/data_pages/new.html.erb
<h1>New Data Page</h1>

<%= render 'form', data_page: @data_page %>

<%= link_to 'Back', data_pages_path %>

app/views/data_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @data_page.data %>
</p>

<%= link_to 'Edit', edit_data_page_path(@data_page) %> |
<%= link_to 'Back', data_pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KaminariSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>